
WIDTH = 1200
HEIGHT = 700

FPS = 30

BLUE = (0, 0, 255)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

COLORS = [BLUE, WHITE, RED, GREEN]

MAX_ASTROIDS = 3


ENEMY_MAXSPEED = 5

BIG_ASTROID = 50
MEDIUM_ASTROID = 35
SMALL_ASTROID = 25

ASTROIDS = [BIG_ASTROID, MEDIUM_ASTROID, SMALL_ASTROID]


####   PLAYER ATTRIBUTES ##############

PLAYER_STARTPOS_X = WIDTH / 2
PLAYER_STARTPOS_Y = HEIGHT / 2
PLAYER_SIZE = (int(WIDTH * 0.06), int(HEIGHT * 0.1))
PLAYER_R = 15
PLAYER_SPEED = 8
PLAYER_MAX_SPEED = 9



BULLET_RADIUS = 5
BULLET_SPEED = 15

SCORE_MULTIPLIER = 1

